#! /bin/sh
### BEGIN INIT INFO
# Provides:          zerod
# Required-Start:    $syslog $time $remote_fs
# Required-Stop:     $syslog $time $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Zerod
# Description:       Zerod
### END INIT INFO
#
#

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/sbin
DAEMON=/usr/sbin/zerod
DAEMON_OPTS="-d -c /etc/zerod.conf"
test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
        log_daemon_msg "Starting Zerod" "zerod"
        start_daemon $DAEMON $DAEMON_OPTS 1>/dev/null 2>/dev/null
        log_end_msg $?
    ;;
  stop)
        log_daemon_msg "Stopping Zerod" "zerod"
        pkill -f "$DAEMON $DAEMON_OPTS"
        log_end_msg $?
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc $DAEMON zerod && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/zerod {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
